---
title: "HPAP_Atlas_Figure_2"
author: "Greg_G"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install Packages}
library(ggplot2)
library(patchwork)
library(ComplexHeatmap)
library(grid)
library(ggridges)
library(png)
```

Commonly Used Plot Paramaeters
```{r Common Plot Parameters}
subplotTheme <- theme(
  axis.title.x = element_text(size = 6),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 6),
  axis.text.y = element_text(size = 6))
```

Blank graph for space filler purposes
```{r Blank graph for filler}
dfFigBlank <- data.frame(x = c(1,2), y = c(3,4))

FigBlank <- dfFigBlank %>%
  ggplot(aes(x,y)) +
  theme_void()
#FigBlank
```

```{r Disease Heatmap}
figDiseaseHeatmap <- readRDS(file = "./outs/rds/DiseaseHeatmap.RDS")
set.seed(9)
figDiseaseHeatmap <- grid.grabExpr(draw(figDiseaseHeatmap, merge_legends = TRUE, 
                                       heatmap_legend_side = "bottom", 
                                       padding = unit(c(0, 0, 0, 0), "in")))
#need to save the heatmap as a grob object for downstream figure creation
```

```{r CD25 in CD4 T cells}
fig_CD25_CD4 <- readRDS(file = "./outs/rds/CD25+ CD4+ T cells boxplots.RDS")
fig_CD25_CD4 <- fig_CD25_CD4 +
  theme(axis.text.x = element_blank(),
        strip.text =  element_text(vjust = 3),
        axis.title.y = element_text(size = 6),
        strip.background.x = element_blank())
```

```{r CD25 in CD8 T cells}
fig_CD25_CD8 <- readRDS(file = "./outs/rds/CD25+ CD8+ T cells boxplots.RDS")
fig_CD25_CD8 <- fig_CD25_CD8 +
  theme(axis.text.x = element_blank(),
        axis.title.y = element_text(size = 6),
        strip.text.x = element_blank())
```

```{r CD38 in CD4 T cells}
fig_CD38_CD4 <- readRDS(file = "./outs/rds/CD38+ CD4+ T cells boxplots.RDS")
fig_CD38_CD4 <- fig_CD38_CD4 +
  theme(axis.text.x = element_blank(),
        axis.title.y = element_text(size = 6),
        strip.text.x = element_blank())
```

```{r CD38 in CD8 T cells}
fig_CD38_CD8 <- readRDS(file = "./outs/rds/CD38+ CD8+ T cells boxplots.RDS")
fig_CD38_CD8 <- fig_CD38_CD8 +
  theme(strip.text.x = element_blank(),
        axis.title.y = element_text(size = 6),
        axis.text.x = element_text(size = 6))
```

```{r Treg-like cells}
figTregBoxPlot <- readRDS(file = "./outs/rds/CD4 Mem Tregs pLN boxplots.RDS")
figTregBoxPlot <- figTregBoxPlot +
   theme(axis.title.y = element_text(size = 6),
         axis.text.x = element_text(size = 6),
         plot.margin = unit(c(0.1, 0.2, 0, 0), "in"))
```

```{r Treg-like Representative Plots}
fig_Tregs_rep <- readPNG(source = "./images_for_import/Tregs_representative.png", native = TRUE)
```

```{r Ridglines CD4 Tem CD27 CD127}
figRidgeCD4Tem <- readRDS(file = "./outs/rds/CD4 Tem CD27-CD127 ridgelines.RDS")
figRidgeCD4Tem <- figRidgeCD4Tem +
  ylab("CD27             CD127") +
  theme(axis.title.y = element_text(size = 8, 
                                    margin = margin(0, 0.05, 0, 0, unit = "in")),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_text(size = 6),
        axis.text.x = element_text(size = 6),
        plot.margin = unit(c(0.075, 0.15, 0.075, -0.1), "in"))
```

```{r Representative CD4 Tem CD27 CD127}
fig_CD4_Tem_repImages <- readPNG(source = "./images_for_import/CD4-Tem-CD27-CD127_representative.png", native = TRUE)
```

```{r Ridglines CD4 Temra CD27 CD127}
figRidgeCD4Temra <- readRDS(file = "./outs/rds/CD4 Temra CD27-CD127 ridgelines.RDS")
figRidgeCD4Temra <- figRidgeCD4Temra +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 6),
        axis.text.x = element_text(size = 6),
        plot.margin = unit(c(0, 0, 0, 0.1), "in"))
```

```{r Representative CD4 Temra CD27 CD127}
fig_CD4_Temra_repImages <- readPNG(source = "./images_for_import/CD4-Temra-CD27-CD127_representative.png", native = TRUE)
```

```{r Ridgelines CD8 Tnl CD27 CD127}
figRidgeCD8Tnl <- readRDS(file = "./outs/rds/CD8 Tnl CD27-CD127 ridgelines.RDS")
figRidgeCD8Tnl <- figRidgeCD8Tnl +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 6),
        axis.text.x = element_text(size = 6),
        plot.margin = unit(c(0, 0, 0, 0.1), "in"))
```

```{r Representative CD8 Tnl CD27 CD127}
fig_CD8_Tnl_repImages <- readPNG(source = "./images_for_import/CD8-Tnl-CD27-CD127_representative.png", native = TRUE)
```

```{r CD4 Tn: pLN}
figCD4_Tn_pLN <- readRDS(file = "./outs/rds/CD4 Tn pLN boxplots.RDS")
figCD4_Tn_pLN <- figCD4_Tn_pLN +
  theme(axis.title.y = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 6))
```

```{r CD4 Tn: mLN}
figCD4_Tn_mLN <- readRDS(file = "./outs/rds/CD4 Tn mLN boxplots.RDS")
figCD4_Tn_mLN <- figCD4_Tn_mLN +
  theme(axis.title.y = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 6))
```

```{r Cytotoxic NK cells}
figNKboxplot <- readRDS(file = "./outs/rds/NK CD56dimCD16+ pLN boxplots.RDS")
figNKboxplot <- figNKboxplot +
  theme(axis.title.y = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 6))
```

```{r NK cells Representative Plots}
fig_NKs_rep <- readPNG(source = "./images_for_import/NKs_representative.png", native = TRUE)
```

```{r CD27+ B cells}
figBboxplot <- readRDS(file = "./outs/rds/B cells CD27+ pLN boxplots.RDS")
figBboxplot <- figBboxplot +
  theme(axis.title.y = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 6))
```

```{r CD27+ B cells Representative Plots}
fig_Bcell_CD27_rep <- readPNG(source = "./images_for_import/Bcells-CD27_representative.png", native = TRUE)
```

Figure Assembly
```{r Figure Assembly}
F2layout <- c(
  patchwork::area(t = 1, l = 1, b = 11, r = 10), #A, figDiseaseHeatmap
  patchwork::area(t = 1, l = 11, b = 2, r = 20), #B fig_CD25_CD4
  patchwork::area(t = 3, l = 11, b = 4, r = 20), #C fig_CD25_CD8
  patchwork::area(t = 5, l = 11, b = 6, r = 20), #D fig_CD38_CD4
  patchwork::area(t = 7, l = 11, b = 8, r = 20), #E fig_CD38_CD8
  patchwork::area(t = 9, l = 11, b = 10, r = 13), #F figTregBoxPlot
  patchwork::area(t = 9, l = 14, b = 10, r = 20), #G filler - Treg rep plots
  patchwork::area(t = 11, l = 12, b = 14, r = 14), #H figRidgeCD4Tem
  patchwork::area(t = 15, l = 12, b = 20, r = 14), #I filler - CD4 Tem CD27/CD127 reps
  patchwork::area(t = 11, l = 15, b = 14, r = 17), #J figRidgeCD4Temra
  patchwork::area(t = 15, l = 15, b = 20, r = 17), #K filler - CD4 Temra CD27/CD127 reps
  patchwork::area(t = 11, l = 18, b = 14, r = 20), #L figRidgeCD8Tnl
  patchwork::area(t = 15, l = 18, b = 20, r = 20), #M filler -CD8 Tnl CD27/CD127 reps
  patchwork::area(t = 12, l = 1, b = 14, r = 5), #N figCD4_Tn_pLN
  patchwork::area(t = 12, l = 6, b = 14, r = 10), #O figCD4_Tn_pLN
  patchwork::area(t = 15, l = 1, b = 17, r = 5), #P figNKboxplot
  patchwork::area(t = 15, l = 6, b = 17, r = 11), #Q filler
  patchwork::area(t = 18, l = 1, b = 20, r = 5), #R filler
  patchwork::area(t = 18, l = 6, b = 20, r = 11) #S filler
)

Figure2 <- wrap_elements(plot = figDiseaseHeatmap) + #A 
  fig_CD25_CD4 + #B
  fig_CD25_CD8 + #C
  fig_CD38_CD4 + #D
  fig_CD38_CD8 + #E
  figTregBoxPlot + #F
  FigBlank + #G placeholder
  inset_element(p = fig_Tregs_rep, left = 0.9, bottom = 0.1, right = 0.1, top = 0.9, 
                align_to = "full", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #G
  wrap_elements(full = figRidgeCD4Tem, clip = FALSE) + #H
  FigBlank + #I placeholder
  inset_element(p = fig_CD4_Tem_repImages, left = 1, bottom = 0, right = 0, top = 1, 
                align_to = "panel", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #I
  wrap_elements(panel = figRidgeCD4Temra) + #J
  FigBlank + #K placeholder
  inset_element(p = fig_CD4_Temra_repImages, left = 1, bottom = 0, right = 0, top = 1, 
                align_to = "panel", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #K
  wrap_elements(panel = figRidgeCD8Tnl) + #L
  FigBlank + #M placeholder
  inset_element(p = fig_CD8_Tnl_repImages, left = 1, bottom = 0, right = 0, top = 1, 
                align_to = "panel", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #M
  wrap_elements(full = figCD4_Tn_pLN) + #N
  wrap_elements(full = figCD4_Tn_mLN) + #O
  wrap_elements(full = figNKboxplot) + #P
  FigBlank + #Q placeholder
  inset_element(p = fig_NKs_rep, left = 0.9, bottom = 0.1, right = 0.1, top = 0.9, 
                align_to = "panel", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #Q
  wrap_elements(full = figBboxplot) + #R
  FigBlank + #S
  inset_element(p = fig_Bcell_CD27_rep, left = 1, bottom = 0.9, right = 0, top = 0.1, 
                align_to = "panel", ignore_tag = TRUE, on_top = FALSE, clip = FALSE) + #S
  plot_layout(design = F2layout) + #layout
  plot_annotation(tag_levels = "A") & #annotation modifications
  theme(plot.tag.position = c(0,1),
    plot.tag = element_text(size = 12,
                              face = "bold", 
                              family = "sans",
                              hjust = 1))
```

Figure Export
```{r Exporting Figure}
ggsave(filename = "Figure2.png",
       plot = Figure2,
       device = "png",
       path = "./outs/figures",
       width = 7.5,
       height = 10,
       units = "in",
       dpi = 600)
```

