---
title: "HPAP_Atlas_Figure_S2"
author: "Greg_G"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install Prerequisite Packages
```{r Packages Installation}
library(ggplot2)
library(patchwork)
library(ComplexHeatmap)
library(grid)
library(ggpubr)
library(png)
```

Blank graph for space filler purposes
```{r Blank graph for filler}
dfFigBlank <- data.frame(x = c(1,2), y = c(3,4))

FigBlank <- dfFigBlank %>%
  ggplot(aes(x,y)) +
  theme_void()
#FigBlank
```

```{r pLN UMAP Flow Cytometry}
figScientistComp <- readRDS(file = "./outs/rds/ScientistComparison.RDS")
figScientistComp <- figScientistComp +
  theme(legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        axis.title.y = element_text(size = 8),
        strip.text.x.bottom = element_text(angle = 45, vjust = 1, hjust = 1),
        strip.clip = "off")
```

```{r Figure S2 Assembly}
FS2layout <- c(
  patchwork::area(t = 1, l = 1, b = 2, r = 10) #Scientist Comparison
)

FigureS2 <- wrap_elements(figScientistComp) + #scientist comparison
  plot_layout(design = FS2layout) #layout
FigureS2
```

Figure Export
```{r Exporting Figure}
ggsave(filename = "FigureS2.png",
       plot = FigureS2,
       device = "png",
       path = "./outs/figures",
       width = 7.5,
       height = 3,
       units = "in",
       dpi = 600)
```
