---
title: "HPAP_Atlas_Figure_1"
author: "Greg_G"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install Prerequisite Packages
```{r Packages Installation}
library(ggplot2)
library(patchwork)
library(ComplexHeatmap)
library(grid)
```

Commonly Used Plot Paramaeters
```{r Common Plot Parameters}
subplotTheme <- theme(
  axis.title.x = element_text(size = 6),
  axis.text.x = element_text(size = 6),
  axis.title.y = element_text(size = 6),
  axis.text.y = element_text(size = 6))
```

Blank graph for annotation purposes
```{r Blank graph for filler}
dfFigBlank <- data.frame(x = c(1,2), y = c(3,4))

FigBlank <- dfFigBlank %>%
  ggplot(aes(x,y)) +
  theme_void()
#FigBlank
```

```{r Lineage Heatmap}
figLineageHeatmap <- readRDS(file = "./outs/rds/LinHeatmap.RDS")

figLineageHeatmap <-grid.grabExpr(draw(figLineageHeatmap, merge_legends = TRUE))
figLineageHeatmap
#need to save the heatmap as a grob object for downstream figure creation
```

```{r Lineage PCA}
figLineagePCA <- readRDS(file = "./outs/rds/LinPCA.RDS")

PCAlegend <- as_ggplot(get_legend(figLineagePCA + theme(legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.05, "in"),
        legend.position = "right",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 4))))
PCAlegend

figLineagePCA <- figLineagePCA +
  subplotTheme +
  theme(legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.05, "in"),
        legend.position = "right",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 4))
```

```{r Lineage PCA BiPlot}
figLineageBiplot <- readRDS(file = "./outs/rds/LinPCAbiplot.RDS")

figLineageBiplot <- figLineageBiplot +
  subplotTheme
  
```

```{r B cells}
figLineageBcells <- readRDS(file = "./outs/rds/Tissues B cells.RDS")

figLineageBcells <- figLineageBcells +
  labs(title = "B cells") +
  subplotTheme +
  xlab(element_blank()) +
  theme(plot.title = element_text(family = "sans", 
                                  face = "bold", 
                                  size = 8,
                                  hjust = 0.5,
                                  vjust = 4))
```

```{r T cells}
figLineageTcells <- readRDS(file = "./outs/rds/Tissues T cells.RDS")

figLineageTcells <- figLineageTcells +
  labs(title = "T cells") +
  subplotTheme +
  xlab(element_blank()) +
  theme(plot.title = element_text(family = "sans", 
                                  face = "bold", 
                                  size = 8,
                                  hjust = 0.5,
                                  vjust = 4))
```

```{r NK cells}
figLineageNKcells <- readRDS(file = "./outs/rds/Tissues NK cells.RDS")

figLineageNKcells <- figLineageNKcells +
  labs(title = "NK cells") +
  subplotTheme +
  xlab(element_blank()) +
  theme(plot.title = element_text(family = "sans", 
                                  face = "bold", 
                                  size = 8,
                                  hjust = 0.5,
                                  vjust = 4))
```

```{r CD8 Tcm}
figLineageCD8Tcm <- readRDS(file = "./outs/rds/Tissues CD8 Tcm.RDS")

figLineageCD8Tcm <- figLineageCD8Tcm +
  labs(title = "CD8+ Tcm cells") +
  subplotTheme +
  xlab(element_blank()) +
  ylab("% of CD8+ T cells") +
  theme(plot.title = element_text(family = "sans", 
                                  face = "bold", 
                                  size = 8,
                                  hjust = 0.5,
                                  vjust = 4))
figLineageCD8Tcm
```

```{r CD8 Tn}
figLineageCD8Tn <- readRDS(file = "./outs/rds/Tissues CD8 Tn.RDS")

figLineageCD8Tn <- figLineageCD8Tn +
  labs(title = "CD8+ Tn cells") +
  subplotTheme +
  xlab(element_blank()) +
  theme(plot.title = element_text(family = "sans", 
                                  face = "bold", 
                                  size = 8,
                                  hjust = 0.5,
                                  vjust = 4))
```

```{r Figure 1 Assembly}
commonMargins <- margin(t = -5, r = -5, b = -5, l = -5)

F1layout <- c(
  area(t = 1, l = 1, b = 2, r = 5), #A
  area(t = 1, l = 6, b = 2, r = 10), #B
  area(t = 1, l = 11, b = 4, r = 20), #C
  area(t = 3, l = 1, b = 4, r = 5), #D
  area(t = 3, l = 6, b = 4, r = 10), #E
  area(t = 5, l = 1, b = 6, r = 5), #F
  area(t = 5, l = 6, b = 6, r = 10), #G
  area(t = 5, l = 11, b = 6, r = 15), #H
  area(t = 5, l = 16, b = 6, r = 20) #I
)

Figure1 <- wrap_elements(FigBlank) + #A
  wrap_elements(FigBlank) + #B
  wrap_elements(panel = figLineageHeatmap) + #C
  wrap_elements(panel = figLineagePCA + theme(plot.margin = margin(t = -5, r = -5, b = -5, l = -5), legend.margin = margin(t = 0, r = 0, b = 0, l = -5))) + #D
  wrap_elements(panel = figLineageBiplot + theme(plot.margin = commonMargins)) + #E
  wrap_elements(panel = figLineageBcells + theme(plot.margin = commonMargins)) + #F
  wrap_elements(panel = figLineageTcells + theme(plot.margin = commonMargins)) + #G
  wrap_elements(panel = figLineageNKcells + theme(plot.margin = commonMargins)) + #H
  wrap_elements(panel = figLineageCD8Tcm + theme(plot.margin = commonMargins)) + #I
  plot_layout(design = F1layout) + #layout
  plot_annotation(tag_levels = "A") & #annotation mods
  theme(plot.tag = element_text(size = 12,
                                face = "bold", 
                                family = "sans")) 
            
Figure1
```

Figure Export
```{r Exporting Figure}
ggsave(filename = "Figure1.png",
       plot = Figure1,
       device = "png",
       path = "./outs/figures",
       width = 7.5,
       height = 5,
       units = "in",
       dpi = 300)
```
