---
title: "HPAP_Flow-Cytometry_Immune-Lineage"
author: "Gregory_Golden"
date: "2023-06-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Section 1: Install Requisite Packages
```{r Section 1: Packages}
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)
library(rstatix)
library(forcats)
library(ComplexHeatmap)
library(circlize)
library(ggrepel)
library(cluster)
```


Section 2: Data from the HPAP Lineage Flow Cytometry Panel (CSV file of percentages) is imported and readied for further analysis
```{r Section 2: Data Import}
df <- read.csv("./data/Lineage_MasterV3.csv", 
               check.names = FALSE,
               stringsAsFactors = FALSE)

df <- select(df, 1:`CD4 Tnaive1- CD127+`)

df <- df %>%
  mutate(across(.cols = "CD45+":ncol(df), .fns = ~ str_replace_all(., "%$", ""))) %>%
  mutate(across(.cols = "CD45+":ncol(df), .fns = ~ as.numeric(.))) %>%
  mutate(across(.cols = "CD45+":ncol(df), .fns = ~ case_when(. < 0.01 ~ 0.005, TRUE ~ as.numeric(.)))) %>%
  mutate("Age" = as.numeric(df$Age)) %>%
  mutate("Aabs" = as.numeric(df$Aabs)) %>%
  mutate(LN_type = case_when(str_detect(Tissue, "_pLN$") ~ "pLN",
                             str_detect(Tissue, "_mLN$") ~ "mLN",
                             Tissue == "Spleen" ~ "Spleen",
                             Tissue == "PBMC" ~ "PBMC",
                             Tissue == "Whole_Blood" ~ "Whole_Blood",
                             Tissue == "Tonsil" ~ "Tonsil",
                             Tissue == "Thymus" ~ "Thymus",
                             Tissue == "Islet_Sup" ~ "Islet")) %>%
  relocate(LN_type, .after = Tissue)

dfLong <- df %>%
  pivot_longer(cols = c(`CD45+`:ncol(.)), names_to = "metric", values_to = "value")

dfFresh <- filter(dfLong, `Fresh/Thawed` == "fresh")

#due to a more specific naive T cell gating strategy, the Tnaive population (CD45RA+CCR7+) was separated into two populations based upon CD27 and CD127 expression: Tnaive1 (CD27+CD127+ naive T cells, bona fide naive) and Tnaive 1- (all other CD45RA+CCR7+ T cells). 
#The Tnaive population will be filtered out, since it encompasses all CD45RA+CCR7+ T cells and is redundant/less specific.
#Tnaive1 will be re-named Tn and Tnaive1- will be renamed Tnl
dfFresh <- dfFresh %>%
  filter(!str_detect(metric, "Tnaive ")) %>%
  filter(!str_detect(metric, "Tnaive$")) %>%
  mutate(metric = str_replace_all(.$metric, "Tnaive1-", "Tnl")) %>%
  mutate(metric = str_replace_all(.$metric, "Tnaive1", "Tn"))

#Thymus and mixed pLN are not standard HPAP tissues, and therefore will be filtered out
dfFresh <- filter(dfFresh, Tissue != "Thymus", Tissue != "pLN_mix_pLN")
```


Section 3: Create commonly used parameters for plot creation
```{r Section 3: Common Plot Parameters}
#shared graph element list for grey/blue/orange ND/AAb/T1D
theme_list <- list(theme_classic(),
        theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black")),
        scale_shape_manual(values = c(22, 21, 23, 24)),
        scale_fill_manual(values = c("#949494", "#2E96FF", "#FF8B3D", "purple")),
        geom_point(size = 2.7, show.legend = FALSE, stroke = 0.5, 
                   color = "grey40",position = position_jitterdodge(
                     jitter.width = 1.2, dodge.width = 0.5)),
        stat_summary(geom = "errorbar",
               fun.min = function(z) {quantile(z, 0.25)},
               fun.max = function(z) {quantile(z, 0.75)},
               width = 0.2,
               size = 1,
               color = "grey20"),
        stat_summary(fun = median,
               geom = "crossbar",
               width = 0.3,
               size = 0.5,
               show.legend = FALSE,
               color = "grey20"))

#shared graph list for stacked bar charts
theme_stacked_chart_list <- list(geom_bar(stat = "identity", position = "dodge"), 
  scale_fill_brewer(),
  scale_y_continuous(limits = c(0,15),
                     expand = c(0,0),
                     minor_breaks = seq(0, 15 , 1)),
  ylab("Number of Donors"),
  geom_text(size = 3.5,
            position = position_dodge(width = 0.9),
            vjust = 1.25),
  theme_classic(),
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black")))
```


Section 4: Compare immune population frequencies between different scientists
```{r Section 4: Scientist Comparisons}
dfScientistStat <- dfFresh %>%
  filter(Staining_Flow_Researcher == "Greg" | Staining_Flow_Researcher == "Alberto") %>%
  filter(LN_type == "pLN") %>%
  filter(`Disease Status` == "ND") %>%
  filter(!str_detect(metric, "Tn CD127.CD27.")) %>% #all filtered values are 0, stats test would fail
  filter(!str_detect(metric, "Tn CD127.")) %>% #all filtered values are 100, stats test would fail
  filter(!str_detect(metric, "Tn CD27.")) %>% #all filtered values are 100, stats test would fail
  group_by(metric) %>%
  wilcox_test(value ~ Staining_Flow_Researcher) %>%
  adjust_pvalue() %>%
  filter(p.adj < 0.05)

ScientistComp <- dfFresh %>%
  filter(metric %in% dfScientistStat$metric) %>%
  filter(`Disease Status` == "ND") %>%
  ggplot(aes(Staining_Flow_Researcher, value, color = Staining_Flow_Researcher)) +
  geom_jitter(size = 1) +
  theme_classic() +
  facet_wrap(~metric, scales = "free_y")

#ScientistComp

#Results show that there are several parameters that differ between researchers, mainly in PD1, HLA-DR, and CD25 on certain CD4+ T cells. This could be due to differential flow cytometery parameter settings on the cytometer (antibody titrations or conjugations did not change between researchers). 
#Populations that were significantly different between researchers were filtered (see below), keeping the researcher's results (Greg) who analyzed the data and compiled it for the manuscript.

ScientistFilter <- c("CD4 Mem PD1+", "CD4 Tcm PD1+", "CD4 Tem PD1+", "CD4 Temra PD1+", "CD4 Tn PD1+", "CD4 Tnl PD1+", "CD4 Tem HLA-DR+", "CD4 Temra HLA-DR+", "CD4 Tcm HLA-DR+", "CD8 Temra HLA-DR+", "CD4 Tem HLA-DR+ CD38+", "CD4 Temra HLA-DR+ CD38+", "CD4 Tcm HLA-DR+ CD38+", "CD8 Temra HLA-DR+ CD38+", "CD4 Tcm CD25+", "CD4 Tnl CD25+")

dfScientistFilter <- dfFresh %>%
  filter(Staining_Flow_Researcher == "Alberto") %>%
  filter(metric %in% ScientistFilter)

dfLineage <- anti_join(dfFresh, dfScientistFilter)
```


Section 5: Tissue Distribution of Immune Populations
```{r Section 5: Tissue Distribution - Commonly used lineage parameters, total lineage df for ggplot}
LineageList <- c("Eosinophils", "Neutrophils", "B cells","ILCs", "Imm. Granulocytes", "HSCs", "DCs", "Monocytes", "NK cells", "T cells", "CD8+ T cells", "CD8 Tcm", "CD8 Tem", "CD8 Temra", "CD8 Tn", "CD8 Tnl", "CD4+ T cells", "CD4 Tcm", "CD4 Tem", "CD4 Temra", "CD4 Tn", "CD4 Tnl", "CD4 Mem Tregs", "CD4 Mem gcTfh", "CD4 Mem mTfh")
LinTissueColors <- list(`Tissue` = c("Whole_Blood" = "red", "Spleen" =  "#BC4749","SMA_mLN" = "#228B22", "MES_mLN" = "#73A942", "Head_pLN" = "#023E8A", "Body_pLN" = "#0777B6", "Tail_pLN" = "#00B4D8"))
LinColorsOnly <- c("#BC4749", "#228B22", "#73A942", "#023E8A", "#0777B6", "#00B4D8")

#generate df for plotting cell populations, filtering out non-standard HPAP tissues
dfLineageFilter <- dfLineage %>%
  filter(Tissue != "PBMC") %>% #removed since PBMCs have artifacts in the neutrophil counts due to long term blood storage
  filter(Tissue != "Islet_Sup") %>% #removed since it is not a standard HPAP tissue
  filter(Tissue != "Whole_Blood") %>% #removed since it is not a standard HPAP tissue
  mutate(metric = str_replace(metric, " \\(%CD45\\+\\)", "")) %>%
  mutate(metric = str_replace(metric, " \\(%CD45\\)", "")) %>%
  mutate(metric = str_replace(metric, " \\(%T cells\\)", " T cells"))

#generate df for plotting lineage cell populations
dfTotalLineageFreq <- filter(dfLineageFilter, metric %in% LineageList)
```

```{r Section 5: Tissue Distribution - Violin plotting all flow cytometry gates across all tissues}
#violin plotting all flow cytometry gates across all HPAP tissues
TissuePheno_AllGates <- dfLineage %>%
  mutate(Tissue = fct_relevel(Tissue, "Whole_Blood", "PBMC","Spleen", "SMA_mLN", "MES_mLN", "Head_pLN", "Body_pLN", "Tail_pLN", "Islet_Sup")) %>%
  ggplot(aes(Tissue, value)) +
  geom_violin(draw_quantiles = c(0.25,0.50,0.75)) +
  facet_wrap(vars(metric), scales = "free_y") +
  theme(strip.text = element_text(size = 6),
        axis.text.x = element_text(angle = 45, hjust = 1))

TissuePheno_AllGates
```

```{r Section 5: Tissue Distribution - Heatmap of major immune population frequency across tissues}
#generate a df that is compatible with heatmap generation
dfHeatmapNorm <- dfLineageFilter %>%
  group_by(metric) %>%
  mutate(z_score = scale(value)) %>%
  select("HPAP Donor":metric,z_score)

#heatmap of major immune cell population distribution across HPAP tissues
LinTissueOrder <- c("Spleen", "Head_pLN", "Body_pLN", "Tail_pLN", "SMA_mLN", "MES_mLN")
SampleVariablesLin <- c("HPAP Donor", "Tissue")

dfTotalLineageHeatmap <- dfHeatmapNorm %>%
  pivot_wider(names_from = metric, values_from = z_score) %>%
  select(SampleVariablesLin, LineageList) %>%
  mutate(Sample_ID = paste("S", as.character(row_number()), sep = "")) %>%
  relocate(Sample_ID, .before = `HPAP Donor`)

dfTotalLineageHeatmap <- as.data.frame(dfTotalLineageHeatmap)
rownames(dfTotalLineageHeatmap) <- dfTotalLineageHeatmap$Sample_ID
dfTotalLineageHeatmap <- select(dfTotalLineageHeatmap, `HPAP Donor`:ncol(dfTotalLineageHeatmap))

dfLinHeatmapMetadata <- select(dfTotalLineageHeatmap, Tissue)

dfTotalLineageHeatmap <- select(dfTotalLineageHeatmap, "Eosinophils":ncol(dfTotalLineageHeatmap))
dfTotalLineageHeatmap <- t(dfTotalLineageHeatmap)

col_fun_LineageHM <- colorRamp2(c(-2, 0, 2), c("blue", "white", "red")) #set maxima at 5th and 95th percentiles
LinAnn <- HeatmapAnnotation(df = dfLinHeatmapMetadata,
                  which = "col",
                  col = LinTissueColors,
                  simple_anno_size = unit(0.1, "in"),
                  height = unit(0.2, "in"),
                  annotation_name_gp = gpar(fontsize = 8),
                  annotation_legend_param = list(
                        title = "Tissue",
                        at = LinTissueOrder,
                        labels = LinTissueOrder,
                        ann_height = unit(0.5, "in"),
                        grid_width = unit(0.1, "in"),
                        labels_gp = gpar(fontsize = 4),
                        title_gp = gpar(fontsize = 6)
                  ))
LinHeatmap <- Heatmap(dfTotalLineageHeatmap,
                      name = "Z-score",
                      col = col_fun_LineageHM,
                      show_column_names = FALSE,
                      top_annotation = LinAnn,
                      cluster_columns = diana,
                      row_names_gp = gpar(fontsize = 6),
                      row_dend_width = unit(0.1, "in"),
                      column_dend_height = unit(0.2, "in"),
                      heatmap_legend_param = list(
                        legend_height = unit(0.5, "in"),
                        grid_width = unit(0.1, "in"),
                        labels_gp = gpar(fontsize = 4),
                        title_gp = gpar(fontsize = 6)
                      ))
draw(LinHeatmap, merge_legends = TRUE)
saveRDS(LinHeatmap, file = "./outs/rds/LinHeatmap.RDS")
```

```{r Section 5: Tissue Distribution - Heatmap of CD8 T cell population frequency across tissues}
#generate heatmap dataframe
LinTissueOrder <- c("Spleen", "Head_pLN", "Body_pLN", "Tail_pLN", "SMA_mLN", "MES_mLN")

dfCD8Heatmap <- dfLineageFilter %>%
  filter(!grepl("Tn CD127.CD27.", metric)) %>%
  filter(!grepl("Tn CD27.", metric)) %>%
  filter(!grepl("Tn CD127.", metric)) %>%
  filter(!grepl("Tnl CD127\\+CD27\\+", metric)) %>%
  filter(grepl("^CD8 ", metric)) %>%
  filter(metric != "CD8+ T cells") %>%
  filter(!grepl("CD8 Mem", metric)) %>%
  mutate(str_replace_all(metric, "CD8 ", "")) %>%
  group_by(metric) %>%
  mutate(z_score = scale(value))  %>%
  select(1:LN_type, metric, z_score) %>%
  pivot_wider(id_cols = `HPAP Donor`:`LN_type`, names_from = metric, values_from = z_score) %>%
  mutate(Sample_ID = paste("S", as.character(row_number()), sep = "")) %>%
  relocate(Sample_ID, .before = `HPAP Donor`) %>%
  as.data.frame()
rownames(dfCD8Heatmap) <- dfCD8Heatmap$Sample_ID

dfCD8HeatmapMetadata <- select(dfCD8Heatmap, Tissue)

dfCD8Heatmap <- select(dfCD8Heatmap, "CD8 Tcm":ncol(dfCD8Heatmap))
dfCD8Heatmap <- t(dfCD8Heatmap)

#Heatmap
col_fun_CD8HM <- colorRamp2(c(-2, 0, 2), c("blue", "white", "red")) #set maxima at 5th and 95th percentiles
CD8Ann <- HeatmapAnnotation(df = dfCD8HeatmapMetadata,
                  which = "col",
                  col = LinTissueColors,
                  annotation_legend_param = list(
                        title = "Tissue",
                        at = LinTissueOrder,
                        labels = LinTissueOrder
                  ))
CD8Heatmap <- Heatmap(dfCD8Heatmap,
                      name = "Z-score",
                      col = col_fun_CD8HM,
                      show_column_names = FALSE,
                      top_annotation = CD8Ann)
draw(CD8Heatmap, merge_legends = TRUE)
```

```{r Section 5: Tissue Distribution - Heatmap of CD4 T cell population frequency across tissues}
#generate heatmap dataframe
LinTissueOrder <- c("Spleen", "Head_pLN", "Body_pLN", "Tail_pLN", "SMA_mLN", "MES_mLN")

dfCD4Heatmap <- dfLineageFilter %>%
  filter(Staining_Flow_Researcher != "Alberto") %>% #differences in flow researcher was significant for many pops in CD4, this researcher had to be filtered out to avoid too many NA values
  filter(!grepl("CD127.CD27.", metric)) %>%
  filter(!grepl("Tn CD27.", metric)) %>%
  filter(!grepl("Tn CD127.", metric)) %>%
  filter(!grepl("HLA-DR. CD38.", metric)) %>%
  filter(grepl("^CD4 ", metric)) %>%
  filter(metric != "CD4+ T cells") %>%
  filter(!grepl("CD4 Mem", metric)) %>%
  mutate(metric = str_replace_all(metric, "CD4 ", "")) %>%
  group_by(metric) %>%
  mutate(z_score = scale(value))  %>%
  select(1:LN_type, metric, z_score) %>%
  pivot_wider(id_cols = `HPAP Donor`:`LN_type`, names_from = metric, values_from = z_score) %>%
  mutate(Sample_ID = paste("S", as.character(row_number()), sep = "")) %>%
  relocate(Sample_ID, .before = `HPAP Donor`) %>%
  as.data.frame()
rownames(dfCD4Heatmap) <- dfCD4Heatmap$Sample_ID

dfCD4HeatmapMetadata <- select(dfCD4Heatmap, Tissue)

dfCD4Heatmap <- select(dfCD4Heatmap, "Tcm":ncol(dfCD4Heatmap))
dfCD4Heatmap <- t(dfCD4Heatmap)

#Heatmap
col_fun_CD4HM <- colorRamp2(c(-2, 0, 2), c("blue", "white", "red")) #set maxima at 5th and 95th percentiles
CD4Ann <- HeatmapAnnotation(df = dfCD4HeatmapMetadata,
                  which = "col",
                  col = LinTissueColors,
                  annotation_legend_param = list(
                        title = "Tissue",
                        at = LinTissueOrder,
                        labels = LinTissueOrder
                  ))
CD4Heatmap <- Heatmap(dfCD4Heatmap,
                      name = "Z-score",
                      col = col_fun_CD4HM,
                      show_column_names = FALSE,
                      top_annotation = CD4Ann,
                      cluster_rows = diana,
                      cluster_columns = diana)
draw(CD4Heatmap, merge_legends = TRUE)
```

```{r Section 5: Tissue Distribution - Heatmap of B cell population frequency across tissues}
LinTissueOrder <- c("Spleen", "Head_pLN", "Body_pLN", "Tail_pLN", "SMA_mLN", "MES_mLN")

dfBHeatmap <- dfLineageFilter %>%
  filter(grepl("B cells", metric)) %>%
  filter(metric != "B cells") %>%
  mutate(metric = str_replace_all(metric, "B cells", "")) %>%
  group_by(metric) %>%
  mutate(z_score = scale(value))  %>%
  select(1:LN_type, metric, z_score) %>%
  pivot_wider(id_cols = `HPAP Donor`:`LN_type`, names_from = metric, values_from = z_score) %>%
  mutate(Sample_ID = paste("S", as.character(row_number()), sep = "")) %>%
  relocate(Sample_ID, .before = `HPAP Donor`) %>%
  as.data.frame()
rownames(dfBHeatmap) <- dfBHeatmap$Sample_ID

dfBHeatmapMetadata <- select(dfBHeatmap, Tissue)

dfBHeatmap <- select(dfBHeatmap, "CD11c+":ncol(dfBHeatmap))
dfBHeatmap <- t(dfBHeatmap)

#Heatmap
col_fun_BHM <- colorRamp2(c(-2, 0, 2), c("blue", "white", "red")) #set maxima at 5th and 95th percentiles
BAnn <- HeatmapAnnotation(df = dfBHeatmapMetadata,
                  which = "col",
                  col = LinTissueColors,
                  annotation_legend_param = list(
                        title = "Tissue",
                        at = LinTissueOrder,
                        labels = LinTissueOrder
                  ))
BHeatmap <- Heatmap(dfBHeatmap,
                      name = "Z-score",
                      col = col_fun_BHM,
                      show_column_names = FALSE,
                      top_annotation = BAnn,
                      cluster_rows = diana,
                      cluster_columns = diana)
draw(BHeatmap, merge_legends = TRUE)
```

```{r Section 5: Tissue Distribution - Statistics of lineage immune populations across tissues}
#create a statistics-friendly df to test significance differences of lineage immune populations across tissues
dfTotalLineageFreqStats <- dfTotalLineageFreq %>%
  pivot_wider(names_from = metric, values_from = value)
colnames(dfTotalLineageFreqStats) <- gsub("\\+ \\(\\%T ?cells\\)", "", colnames(dfTotalLineageFreqStats))
colnames(dfTotalLineageFreqStats) <- gsub(" ", "_", colnames(dfTotalLineageFreqStats))

#use Dunn's test on every major lineage cell population to look for statistical differences between tissues
colnameTissue <- names(dfTotalLineageFreqStats)[3] #the Tissue column name
LineageListStats <- dfTotalLineageFreqStats[14:ncol(dfTotalLineageFreqStats)] %>%
  colnames()
  

LineageFreqStats <- lapply(LineageListStats, function(x) {
  rstatix::dunn_test(dfTotalLineageFreqStats, reformulate(colnameTissue, x))
})

dfLineageFreqStats <- bind_rows(LineageFreqStats)
```

```{r Section 5: Tissue Distribution - Frequency of lineage cell populations by tissue site}
TotalLineageFreq <- dfTotalLineageFreq %>%
  mutate(Tissue = fct_relevel(Tissue, "Spleen", "SMA_mLN", "MES_mLN", "Head_pLN", "Body_pLN", "Tail_pLN")) %>%
  ggplot(aes(Tissue, value)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(width = 0.3,size = 0.5) +
  ylab("% of Parent") +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(size = 8)
  ) +
  scale_color_manual(values = LinColorsOnly) +
  facet_wrap(vars(metric), scales = "free_y")

TotalLineageFreq
```

```{r Section 5: Tissue Distribution - B, T, NK cells, ILCs, CD8 Tcm, CD8 Tn across tissues}
#these populations were selected based upon similarity across subsets (B cells), differences between spleen and all LNs (T cells, CD8 Tn), and subtle differences among LNs (NK cells, ILCs, and CD8 Tcm)
LinPops <- c("B cells", "T cells", "NK cells", "ILCs", "CD8 Tcm", "CD8 Tn")

LinPopsGraphs <- lapply(LinPops, function(l) {
  message(paste("Generating graph for", l, "across tissues"), sep = "")
  lplot <- dfTotalLineageFreq %>%
    filter(metric == as.character(l)) %>%
    mutate(Tissue = str_replace(Tissue, "_", " ")) %>%
    mutate(Tissue = fct_relevel(Tissue, "Spleen", "SMA mLN", "MES mLN", "Head pLN", "Body pLN", "Tail pLN")) %>%
    ggplot(aes(Tissue, value, color = Tissue)) +
    geom_boxplot(width = 0.8,
               outlier.shape = NA,
               show.legend = FALSE) +
    geom_point(
    size = 1,
    stroke = 0.2,
    alpha = 0.4,
    show.legend = FALSE,
    position = position_jitterdodge(jitter.width = 1, 
                                    dodge.width = 0.8)) +
    scale_color_manual(values = LinColorsOnly) +
    ylab("% of CD45+ cells") +
    theme_classic() +
    theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(size = 8)
    )
  saveRDS(lplot, file = paste0("./outs/rds/Tissues ", as.character(l),".RDS"))
})
```

```{r Section 5: Tissue Distribution - Generate df's for B cell, CD4+ T cell, CD8+ T cell, and NK cells}
#B cell df
dfBcellPopsFreq <- dfLineageFilter %>%
  filter(grepl("^B cells", metric)) %>%
  filter(metric != "B cells (%CD45)")

#B cell stats df
dfBcellPopsStats <- dfBcellPopsFreq %>%
  pivot_wider(names_from = metric, values_from = value)
colnames(dfBcellPopsStats) <- gsub("\\+", "pos", colnames(dfBcellPopsStats))
colnames(dfBcellPopsStats) <- gsub(" ", "_", colnames(dfBcellPopsStats))
colnames(dfBcellPopsStats) <- gsub("\\-", "neg", colnames(dfBcellPopsStats))

BcellListStats <- dfBcellPopsStats %>%
  select(B_cells_CD11cpos:ncol(dfBcellPopsStats)) %>%
  colnames()

BcellFreqStats <- lapply(BcellListStats, function(x) {
  rstatix::dunn_test(dfBcellPopsStats, reformulate("Tissue", x))
})

dfBcellFreqStats <- bind_rows(BcellFreqStats)

#CD4+ T cell df
dfCD4TcellPopsFreq <- dfLineageFilter %>%
  filter(grepl("^CD4", metric)) %>%
  filter(metric != "CD4+ T cells") %>%
  filter(metric != "CD45+")

#CD4+ T cell stats df
dfCD4TcellPopsStats <- dfCD4TcellPopsFreq %>%
  filter(!grepl("Tn CD127.CD27.", metric)) %>%
  filter(!grepl("Tn CD27.", metric)) %>%
  filter(!grepl("Tn CD127.", metric)) %>%
  filter(!grepl("Tnl CD127\\+CD27\\+", metric)) %>%
  pivot_wider(names_from = metric, values_from = value)
colnames(dfCD4TcellPopsStats) <- gsub("\\+", "pos", colnames(dfCD4TcellPopsStats))
colnames(dfCD4TcellPopsStats) <- gsub(" ", "_", colnames(dfCD4TcellPopsStats))
colnames(dfCD4TcellPopsStats) <- gsub("\\-", "neg", colnames(dfCD4TcellPopsStats))

CD4TcellListStats <- dfCD4TcellPopsStats %>%
  select(CD4_Mem_gcTfh:ncol(dfCD4TcellPopsStats)) %>%
  colnames()

CD4TcellFreqStats <- lapply(CD4TcellListStats, function(x) {
  rstatix::dunn_test(dfCD4TcellPopsStats, reformulate("Tissue", x))
})

dfCD4TcellFreqStats <- bind_rows(CD4TcellFreqStats)

#CD8+ T cell df
dfCD8TcellPopsFreq <- dfLineageFilter %>%
  filter(grepl("^CD8", metric)) %>%
  filter(metric != "CD8+ T cells")

#CD8+ T cell stats df
dfCD8TcellPopsStats <- dfCD8TcellPopsFreq %>%
  filter(!grepl("Tn CD127.CD27.", metric)) %>%
  filter(!grepl("Tn CD27.", metric)) %>%
  filter(!grepl("Tn CD127.", metric)) %>%
  filter(!grepl("Tnl CD127\\+CD27\\+", metric)) %>%
  pivot_wider(names_from = metric, values_from = value)
colnames(dfCD8TcellPopsStats) <- gsub("\\+", "pos", colnames(dfCD8TcellPopsStats))
colnames(dfCD8TcellPopsStats) <- gsub(" ", "_", colnames(dfCD8TcellPopsStats))
colnames(dfCD8TcellPopsStats) <- gsub("\\-", "neg", colnames(dfCD8TcellPopsStats))

CD8TcellListStats <- dfCD8TcellPopsStats %>%
  select(CD8_Mem_CD127negCD27neg:ncol(dfCD8TcellPopsStats)) %>%
  colnames()

CD8TcellFreqStats <- lapply(CD8TcellListStats, function(x) {
  rstatix::dunn_test(dfCD8TcellPopsStats, reformulate("Tissue", x))
})

dfCD8TcellFreqStats <- bind_rows(CD8TcellFreqStats)

#NK cell df
dfNKcellPopsFreq <- dfLineageFilter %>%
  filter(grepl("NK CD56", metric)) 

#NK cell stats df
dfNKcellPopsStats <- dfNKcellPopsFreq %>%
  pivot_wider(names_from = metric, values_from = value)
colnames(dfNKcellPopsStats) <- gsub("\\+", "pos", colnames(dfNKcellPopsStats))
colnames(dfNKcellPopsStats) <- gsub(" ", "_", colnames(dfNKcellPopsStats))
colnames(dfNKcellPopsStats) <- gsub("\\-", "neg", colnames(dfNKcellPopsStats))

NKcellListStats <- dfNKcellPopsStats %>%
  select(NK_CD56briCD16neg:ncol(dfNKcellPopsStats)) %>%
  colnames()

NKcellFreqStats <- lapply(NKcellListStats, function(x) {
  rstatix::dunn_test(dfNKcellPopsStats, reformulate("Tissue", x))
})

dfNKcellFreqStats <- bind_rows(NKcellFreqStats)
```

```{r Section 5: Tissue Distribution - Graphing B, T, and NK subsets of interest across tissues}
#create a vector of immune subsets that were statistically different across LN types
TissueSigPops <- c("B cells CD11c+", "CD4 Tem CD38+", "CD8 Tem PD1+", "CD8 Tcm", "CD4 Tem CD38+")

TissueSigPopsGraphs <- lapply(TissueSigPops, function(i) {
  message(paste("Generating graph for", i, "across tissues"), sep = "")
  iplot <- dfLineageFilter %>%
    filter(metric == as.character(i)) %>%
    mutate(Tissue = str_replace(Tissue, "_", " ")) %>%
    mutate(Tissue = fct_relevel(Tissue, "Spleen", "SMA mLN", "MES mLN", "Head pLN", "Body pLN", "Tail pLN")) %>%
    ggplot(aes(Tissue, value, color = Tissue)) +
    geom_boxplot(width = 0.8,
               outlier.shape = NA,
               show.legend = FALSE) +
    geom_point(
    size = 1,
    stroke = 0.2,
    alpha = 0.4,
    show.legend = FALSE,
    position = position_jitterdodge(jitter.width = 0.3, 
                                    dodge.width = 0.8)) +
    scale_color_manual(values = LinColorsOnly) +
    ylab("% of parent") +
    theme_classic() +
    theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y = element_text(size = 8)
    )
})
```

```{r Section 5: Tissue Distribution - Generate PCA-compatible dataframe and metadata for entire dataset}
#PCA compatible dataframe for the entire dataset
dfPCA <- dfLineageFilter %>%
  select(1:Tissue, metric:ncol(dfLineage)) %>%
  pivot_wider(id_cols = `HPAP Donor`:`Tissue`, names_from = metric, values_from = value) %>%
  mutate(Sample_ID = paste("S", as.character(row_number()), sep = "")) %>%
  relocate(Sample_ID, .before = `HPAP Donor`) %>%
  as.data.frame()
rownames(dfPCA) <- dfPCA$Sample_ID

dfPCAMetadata <- select(dfPCA, Tissue, `HPAP Donor`) 
dfPCAMetadata$Sample_ID <- rownames(dfPCAMetadata)
```

```{r Section 5: Tissue Distribution - Generate PCA plots/biplots to examine tissue immune lineage differences}
#PCA for immune lineage
dfLineagePCA <- select(dfPCA, LineageList)
TotalLinPCA <- prcomp(dfLineagePCA, scale. = TRUE)

dfTotalLinPCA <- TotalLinPCA$x %>%
  as.data.frame() %>%
  mutate(Sample_ID = rownames(dfLineagePCA)) %>%
  full_join(dfPCAMetadata, by = "Sample_ID")

Lin_var_explained <- TotalLinPCA$sdev^2/sum(TotalLinPCA$sdev^2)

TotalLinPCAplot <- dfTotalLinPCA %>%
  mutate(Tissue = str_replace(Tissue, "_", " ")) %>%
  mutate(Tissue = fct_relevel(Tissue, "Spleen", "SMA mLN", "MES mLN", "Head pLN", "Body pLN", "Tail pLN")) %>%
  ggplot(aes(PC1, PC2, color = Tissue)) +
  geom_point(size = 0.5) +
  #geom_text(label = dfTotalLinPCA$`HPAP Donor`, nudge_y = TRUE) +
  labs(x=paste0("PC1: ",round(Lin_var_explained[1]*100,1),"%"),
       y=paste0("PC2: ",round(Lin_var_explained[2]*100,1),"%")) +
  scale_color_manual(values = LinColorsOnly) +
  theme_classic()

TotalLinPCAplot
saveRDS(TotalLinPCAplot, file = "./outs/rds/LinPCA.RDS")

dfTotalLinBiplot <- TotalLinPCA$rotation %>%
  as.data.frame() %>%
  mutate(Population = rownames(TotalLinPCA$rotation))
  
TotalLinBiPlot <- dfTotalLinBiplot %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(aes(x = 0, y = 0, xend = dfTotalLinBiplot$PC1, yend = dfTotalLinBiplot$PC2), 
               arrow = arrow(angle = 20, 
                             length = unit(0.02, "inches"),
                             ends = "last",
                             type = "closed"),
               color = "grey",
               linewidth = 0.2) +
  geom_text_repel(label = dfTotalLinBiplot$Population, 
                  size = 1, 
                  min.segment.length = 0.2,
                  segment.color = "darkblue",
                  segment.alpha = 0.5,
                  segment.size = 0.2) +
  theme_classic()
TotalLinBiPlot
saveRDS(TotalLinBiPlot, file = "./outs/rds/LinPCAbiplot.RDS")
```

```{r Section 5: Tissue Distribution - Generate PCA plots/biplots to examine tissue CD4+ T cell differences}
pcaCD4Pops <- c()
pcaCD4Pops <- append(pcaCD4Pops, str_match(colnames(dfPCA), "^CD4 .*$"))
pcaCD4Pops <- pcaCD4Pops[!is.na(pcaCD4Pops)]
pcaCD4Pops <- pcaCD4Pops %>%
  str_remove("CD4 Tn CD127.CD27.") %>%
  str_remove("CD4 Tn CD27.") %>%
  str_remove("CD4 Tn CD127.") %>%
  str_remove("CD4 Tnl CD127\\+CD27\\+") %>%
  str_remove("^CD4 Mem .*$")
pcaCD4Pops <- pcaCD4Pops[pcaCD4Pops != ""]


#MAJOR ISSUE: because there were significant differences between researchers, some populations were omitted from the dataset. These produce NA values, and therefore the prcomp function must use a dataframe that either omits the rows or the columns with NA. Both options are explored below...

#filtering out Alberto's samples
dfCD4forPCA <- dfPCA %>%
  filter(Tissue != "Spleen") %>%
  filter(!is.na(`CD4 Tcm CD25+`)) %>%
  select(pcaCD4Pops)

CD4PCA <- prcomp(dfCD4forPCA, scale. = TRUE)

dfCD4PCA <- CD4PCA$x %>%
  as.data.frame() %>%
  mutate(Sample_ID = rownames(dfCD4forPCA)) %>%
  full_join(dfPCAMetadata, by = "Sample_ID")

CD4_var_explained <- CD4PCA$sdev^2/sum(CD4PCA$sdev^2)

CD4PCAplot <- dfCD4PCA %>%
  ggplot(aes(PC4, PC5, color = Tissue)) +
  geom_point(size = 4) +
  geom_text(label = dfCD4PCA$`HPAP Donor`, nudge_y = TRUE) +
  labs(x=paste0("PC3: ",round(Lin_var_explained[4]*100,1),"%"),
       y=paste0("PC4: ",round(Lin_var_explained[5]*100,1),"%")) +
  theme_classic()

CD4PCAplot

dfCD4Biplot <- CD4PCA$rotation %>%
  as.data.frame() %>%
  mutate(Population = rownames(CD4PCA$rotation))
  
CD4BiPlot <- dfCD4Biplot %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(aes(x = 0, y = 0, xend = dfCD4Biplot$PC1, yend = dfCD4Biplot$PC2), 
               arrow = arrow(angle = 60, 
                             length = unit(0.1, "inches"),
                             ends = "last",
                             type = "closed")) +
  geom_text_repel(label = dfCD4Biplot$Population) +
  theme_classic()
CD4BiPlot
```

```{r Lineage Data Export}
HPAP_Lineage_export <- dfLineage %>%
  distinct(`HPAP Donor`, `Disease Status`, Tissue, LN_type, Sex, Age, Aabs, GADpos) %>%
  filter(Tissue != "PBMC") %>% #removed since PBMCs have artifacts in the neutrophil counts due to long term storage
  filter(Tissue != "Islet_Sup") %>% #removed since it is not a standard HPAP tissue
  filter(Tissue != "Whole_Blood") 

write.csv(HPAP_Lineage_export, "~/Betts_Code/T1D-Immuno-Atlas/data/HPAP_Lineage_export.csv", row.names = FALSE)
```

```{r Exploring Multinomial Logistic Regression}
library(nnet)
library(GGally)

dflmtest <- select(dfTotalLineageFreqStats, 1:`Age`, CD8_Tn) %>%
  select(Disease_Status, Tissue, Sex, Age, CD8_Tn) %>%
  mutate(Tissue = fct_relevel(Tissue, "Spleen", "SMA_mLN", "MES_mLN", "Head_pLN", "Body_pLN", "Tail_pLN")) %>%
  mutate(Sex = fct_relevel(Sex, "M", "F")) %>%
  mutate(Disease_Status = fct_relevel(Disease_Status, "ND", "AAb+", "T1D"))

GGally::ggpairs(dflmtest)

lmCD8Tcm <- lm(Diseas)

```

