---
title: "T1D-Immune-Atlas_Lineage-flow_221021"
author: "Greg_G"
date: "2022-10-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Section 1: Install Requisite Packages
```{r Packages}
library(dplyr)
library(tidyr)
library(ggplot2)
```

Section 2: Data from the HPAP Lineage Flow Cytometry Panel (CSV of percentages) is imported and readied for further analysis
```{r Data Import}
df <- read.csv("./data/Lineage_MasterV2.csv", 
               check.names = FALSE,
               stringsAsFactors = FALSE)

df <- df %>%
  mutate("Age" = as.numeric(df$Age)) %>%
  mutate("Aabs" = as.numeric(df$Aabs)) %>%
  mutate(Donor = gsub("-", "", Donor)) %>%
  mutate(Disease_Status = factor(Disease_Status, levels = c("ND", "AAb+", "T1D"))) %>%
  mutate(LN_type = case_when(Tissue == "BODY_LN" | Tissue == "HEAD_LN" | Tissue == "Tail_LN" ~ "pLNs",
        Tissue == "SMA_LN" | Tissue == "MES_LN" ~ "mesLNs", Tissue == "Spleen" ~ "Spleen")) %>%
  relocate(LN_type, .after = Tissue)

df <- df %>%
  pivot_longer(cols = c(14:ncol(.)), names_to = "metric", values_to = "percent")

dfFresh <- filter(df, Fresh_Thawed == "fresh")
```

Section 3: Create commonly used parameters for plot creation
```{r Common Plot Parameters}
#shared graph element list for grey/blue/orange ND/AAb/T1D
theme_list <- list(theme_classic(),
        theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black")),
        scale_shape_manual(values = c(22, 21, 23)),
        scale_fill_manual(values = c("#949494", "#2E96FF", "#FF8B3D")),
        geom_point(size = 2.7, show.legend = FALSE, stroke = 0.5, 
                   color = "grey40",position = position_jitterdodge(
                     jitter.width = 1.2, dodge.width = 0.5)),
        stat_summary(geom = "errorbar",
               fun.min = function(z) {quantile(z, 0.25)},
               fun.max = function(z) {quantile(z, 0.75)},
               width = 0.2,
               size = 1,
               color = "grey20"),
        stat_summary(fun = median,
               geom = "crossbar",
               width = 0.3,
               size = 0.5,
               show.legend = FALSE,
               color = "grey20"))

#shared graph list for stacked bar charts
theme_stacked_chart_list <- list(geom_bar(stat = "identity", position = "dodge"), 
  scale_fill_brewer(),
  scale_y_continuous(limits = c(0,15),
                     expand = c(0,0),
                     minor_breaks = seq(0, 15 , 1)),
  ylab("Number of Donors"),
  geom_text(size = 3.5,
            position = position_dodge(width = 0.9),
            vjust = 1.25),
  theme_classic(),
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black")))
```

Section 4: Plotting donor cohort summaries
```{r Plotting Donor Summaries}
#make a table for simple donor summaries
dfDonors <- dfFresh %>%
  distinct(Donor, Disease_Status, Age, Sex, Aabs, GADpos, LOD)

#Number of Donors by Sex per Disease Group
sexCount <- count(dfDonors, Disease_Status, Sex)

donorN <- ggplot(sexCount, aes(x = Disease_Status, y = n, fill = Sex, label = n)) +
  theme_stacked_chart_list + 
  scale_y_continuous(limits = c(0,10),
                     expand = c(0,0))

donorN
plot <- "donorN"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorN,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.4 * number_of_cats,
  height = 3,
  units = "in",
  dpi = 300)

#Donor age by disease status
donorAge <- ggplot(dfDonors, aes(Disease_Status, Age, 
                                 shape = Disease_Status, 
                                 fill = Disease_Status)) +
  scale_y_continuous(limits = c(0,40),
                     expand = c(0,0)) +
  #xlab("Disease Status") +
  ylab("Donor Age (years)") +
  theme_list

donorAge
plot <- "donorAge"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorAge,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.2 * number_of_cats,
  height = 3,
  units = "in",
  dpi = 300)

# number of AAbs for each disease group (red outlined is GAD+)
aabCount <- count(dfDonors, Disease_Status, Aabs) %>%
  complete(Disease_Status, Aabs, fill = list(n = 0))
aabCountLabel <- mutate(aabCount, n = ifelse(n == 0, 0, NA))

donorAAbs <- ggplot(aabCount, aes(Disease_Status, n,
                                  fill = Aabs,
                                  label = n)) +
  geom_col(position = position_dodge2(preserve = "single", width = 0.9), color = "grey20") +
  scale_fill_distiller(direction = 1) +
  scale_y_continuous(limits = c(-0.05,15.2), expand = c(0,0)) +
  ylab("Number of Donors") +
  geom_text(data = aabCountLabel, position = position_dodge2(width = 0.9),
    vjust = -0.5, size = 3.5)  +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black"))

donorAAbs
plot <- "donorAAbs"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorAAbs,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.6 * number_of_cats,
  height = 2.5,
  units = "in",
  dpi = 300)

#Length of Disease Plot for T1D group
lod_aab <- ggplot(dfDonors, aes(LOD, Aabs)) +
  geom_point(size = 2) +
  xlab("Years Post-Diagnosis") +
  ylab("Number of AAbs") +
  scale_y_continuous(limits = c(-0.1,4.2), expand = c(0,0)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 14, vjust = 1),
        axis.title.y = element_text(size = 14, vjust = 1),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black"))

lod_aab
plot <- "lod_aab"
ggsave(filename = plot,
  plot = lod_aab,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 5,
  height = 3,
  units = "in",
  dpi = 300)

#Creating a dataframe to visualize the fraction of HPAP donors with certain tissue samples
dfTissues <- dfFresh %>%
  select(c(1,2,3)) %>%
  distinct() %>%
  pivot_wider(names_from = Tissue, values_from = Tissue) %>%
  mutate(pLNs = case_when(BODY_LN == "BODY_LN" | HEAD_LN == "HEAD_LN" | Tail_LN == "Tail_LN" ~ TRUE)) %>%
  mutate(mesLNs = case_when(MES_LN == "MES_LN" | SMA_LN == "SMA_LN" ~ TRUE)) %>%
  mutate(SPLEEN = case_when(Spleen == "Spleen" ~ TRUE)) %>%
  mutate(PMS = case_when(pLNs & mesLNs & SPLEEN ~ TRUE)) %>%
  mutate(PS = case_when(pLNs & SPLEEN ~ TRUE)) %>%
  mutate(MS = case_when(pLNs & SPLEEN ~ TRUE)) %>%
  mutate(all = case_when(BODY_LN == "BODY_LN" & HEAD_LN == "HEAD_LN" & Tail_LN == "Tail_LN" &
                          MES_LN == "MES_LN" & SMA_LN == "SMA_LN" & Spleen == "Spleen" ~ TRUE)) %>%
  mutate(all_pLN = case_when(BODY_LN == "BODY_LN" & HEAD_LN == "HEAD_LN" & Tail_LN == "Tail_LN" ~ TRUE))

#Plotting how many donors have at least one pLN, one mesenteric LN, and Spleen
dfPMSTissues <- count(dfTissues, Disease_Status, PMS)
dfPMSTissues <- mutate(dfPMSTissues, PMS = replace_na(dfPMSTissues$PMS, FALSE))

donorPMS <- ggplot(dfPMSTissues, aes(x = Disease_Status, y = n, fill = PMS, label = n)) +
  theme_stacked_chart_list

donorPMS
plot <- "donorPMS"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorPMS,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.2 * number_of_cats,
  height = 3,
  units = "in",
  dpi = 300)

#Plotting how many donors have all pLN, all mesenteric LN, and Spleen
dfAllTissues <- count(dfTissues, Disease_Status, all)
dfAllTissues <- mutate(dfAllTissues, all = replace_na(dfAllTissues$all, FALSE))

donorAllTissues <- ggplot(dfAllTissues, aes(x = Disease_Status, y = n, fill = all, label = n)) +
  theme_stacked_chart_list

donorAllTissues
plot <- "donorAllTissues"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorAllTissues,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.2 * number_of_cats,
  height = 3,
  units = "in",
  dpi = 300)

#Plotting how many donors have all pLN
dfpLNTissues <- count(dfTissues, Disease_Status, all_pLN)
dfpLNTissues <- mutate(dfpLNTissues, all_pLN = replace_na(dfpLNTissues$all_pLN, FALSE)) %>%
  complete(Disease_Status, all_pLN, fill = list(n = 0))

donorpLN <- ggplot(dfpLNTissues, aes(x = Disease_Status, y = n, fill = all_pLN, label = n)) +
  theme_stacked_chart_list

donorpLN
plot <- "donorPLN"
number_of_cats <- 3
ggsave(filename = plot,
  plot = donorpLN,
  path = "~/Betts_Code/T1D-Immuno-Atlas/outs/pdf/221026_3groups/",
  device = "pdf",
  width = 1.2 * number_of_cats,
  height = 3,
  units = "in",
  dpi = 300)


```

